server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
      default-filters:
        - AddResponseHeader=source, Levi


#spring:
#  cloud:
#    gateway:
#      routes:
##        - id: after_route
##          uri: https://nps.withlevi.top
##          predicates:
##            - After=2023-11-27T22:20:47.789+08:00[Asia/Shanghai]
##        - id: before_route
##          uri: https://blog.withlevi.top
##          predicates:
##            - Before=2023-11-27T22:20:47.789+08:00[Asia/Shanghai]

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: add_request_header_route
#          uri: http://localhost:8123
#          predicates:
#            - Path=/api/name/**
#          filters:
#            - AddRequestHeader=Levi, Xiaoxiaolovexmj
#            - AddRequestParameter=name, LoveLevi


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace