server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: https://nps.withlevi.top
          predicates:
            - After=2023-11-27T22:20:47.789+08:00[Asia/Shanghai]
        - id: before_route
          uri: https://blog.withlevi.top
          predicates:
            - Before=2023-11-27T22:20:47.789+08:00[Asia/Shanghai]
